//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /memberlist.php?&amp;order=desc&amp;sort=posts&amp;page={0}&amp;act=members HTTP/1.1
        ///User-Agent: Opera/9.63 (Windows NT 5.1; U; en) Presto/2.1.1
        ///Host: forum.codenet.ru
        ///Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
        ///Accept-Language: ru,en;q=0.9,fi-FI;q=0.8,fi;q=0.7
        ///Accept-Charset: iso-8859-1, utf-8, utf-16, *;q=0.1
        ///Accept-Encoding: deflate, gzip, x-gzip, identity, *;q=0
        ///Cookie: b=b; bblastvisit=1233577963; bbforum_view=c790b490850932b5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _Get {
            get {
                return ResourceManager.GetString("_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /private.php?do=newpm HTTP/1.1
        ///User-Agent: Opera/9.62 (Windows NT 5.1; U; en) Presto/2.1.1
        ///Host: forum.codenet.ru
        ///Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
        ///Accept-Language: ru,fi;q=0.9,en;q=0.8,ru-RU;q=0.7
        ///Accept-Charset: iso-8859-1, utf-8, utf-16, *;q=0.1
        ///Accept-Encoding: deflate, gzip, x-gzip, identity, *;q=0
        ///Cookie: bblastvisit=1231957409; bblastactivity=0; bbuserid=46416; bbpassword=73a9390b7cf635b07b10460b122 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _get2 {
            get {
                return ResourceManager.GetString("_get2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST /private.php?do=insertpm&amp;pmid=0 HTTP/1.1
        ///User-Agent: Opera/9.63 (Windows NT 5.1; U; en) Presto/2.1.1
        ///Host: forum.codenet.ru
        ///Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
        ///Accept-Language: ru,en;q=0.9,fi-FI;q=0.8,fi;q=0.7
        ///Accept-Charset: iso-8859-1, utf-8, utf-16, *;q=0.1
        ///Accept-Encoding: deflate, gzip, x-gzip, identity, *;q=0
        ///Referer: http://forum.codenet.ru/private.php?do=insertpm&amp;pmid=
        ///Cookie: b=b; bblastvisit=1233 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _post {
            get {
                return ResourceManager.GetString("_post", resourceCulture);
            }
        }
    }
}
